grasp_ckpt_path: logs/grasp_ckpt_epoch010.tar

log:
  log_dir: logs/demo_grasp
  exp_name: epoch010

demo:
  scene: 0
  anno: 0
  select_id: [0, 10, 20, 30]   # -1 will draw all the pred mask on one image, or will only draw the corresponding mask
  pc: pc_ws  # pc_ws | pc | seed, use the full reconstructed scene or point cloud
  infer: True  # True | False
  eval: False
  vis: True  # vis point cloud and grasps
  vis_grasp: True

device:
  use_gpu: True
  gpu_id: '0'

data:
  graspnet_root: /data1/datasets/graspnet
  camera_type: kinect
  voxel_size: 0.005  # for mink point cloud sparse conv
  num_points: 15000
  topk: 256   # use topk grasp regions
  topk_th: 0.38
  nms: 2
  fps_num: 2048  # select fps_num grasp regions for fps sampling to get topk grasp regions

model:
  gp_num: 1024
  candidate_num: 5000   # 5000 if aug_sample > 0 else 2048
  rp_num: 256  # 256 if aug_sample > 0 else 64
  aug_sample: 16  # perform aug sample if aug_sample > 0
  region_fps: 16